name: Managing Secrets

on:
    push:

jobs:
    echo_job:
        runs-on: ubuntu-latest
        steps:
            - name: Read Masked Secret
              run: echo ${{ secrets.dev_api_key }}

            - name: Read Secret Content
              run: echo ${{ secrets.dev_api_key }} | sed 's/ //g'