name: Managing Secrets

on:
    push:

jobs:
    echo_job:
        runs-on: ubuntu-latest
        steps:
            - name: echo secret
              run: echo ${{ secrets.dev_api_key }} | sed 's/./& /g'